// <auto-generated />
using System;
using GinosGelato.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GinosGelato.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727131604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GinosGelato.Models.Flavor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Flavors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#F3E5AB",
                            Description = "Classic vanilla with Madagascar beans",
                            Name = "Vanilla Dream"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#5C4033",
                            Description = "Rich dark chocolate delight",
                            Name = "Chocolate Fudge"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FC5A8D",
                            Description = "Fresh strawberries and cream",
                            Name = "Strawberry Bliss"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#98FF98",
                            Description = "Cool mint with chocolate chips",
                            Name = "Mint Chocolate Chip"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#D9D9D9",
                            Description = "Crushed Oreo cookies in vanilla",
                            Name = "Cookies & Cream"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#8B5A2B",
                            Description = "Chocolate with marshmallows & nuts",
                            Name = "Rocky Road"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#7B68EE",
                            Description = "Mixed berry explosion",
                            Name = "Berry Burst"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#93C572",
                            Description = "Authentic Italian pistachio",
                            Name = "Pistachio"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#FFF44F",
                            Description = "Refreshing lemon zest",
                            Name = "Lemon Sorbet"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#C68E17",
                            Description = "Sweet caramel with sea salt",
                            Name = "Salted Caramel"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#6F4E37",
                            Description = "Espresso with coffee bean crunch",
                            Name = "Coffee Crunch"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#FF9AA2",
                            Description = "Colorful fruit sherbet mix",
                            Name = "Rainbow Sherbet"
                        });
                });

            modelBuilder.Entity("GinosGelato.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GinosGelato.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Flavors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LinePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Toppings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GinosGelato.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rainbow Sprinkles",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chocolate Chips",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crushed Oreos",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Caramel Sauce",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hot Fudge",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Whipped Cream",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cherry",
                            Price = 0.25m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Crushed Nuts",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fresh Strawberries",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gummy Bears",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Coconut Flakes",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Graham Cracker",
                            Price = 0.75m
                        });
                });

            modelBuilder.Entity("GinosGelato.Models.OrderItem", b =>
                {
                    b.HasOne("GinosGelato.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GinosGelato.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
