import { test, expect } from '@playwright/test';

test('Waffle Cone', async ({ page }) => {
  await page.goto('https://zealous-sky-008ca630f.1.azurestaticapps.net/');
  await page.getByRole('button', { name: '🎨 Start Creating Your Ice' }).click();
  await page.getByRole('heading', { name: 'Waffle Cone' }).click();
  await page.getByText('🍪Cookies & CreamCrushed Oreo').click();
  await page.getByText('🧈Salted CaramelSweet caramel').click();
  await page.locator('div').filter({ hasText: /^☕Hot Fudge\+\$0\.75$/ }).first().click();
  await page.locator('div').filter({ hasText: /^🌈Rainbow Sprinkles\+\$0\.50$/ }).first().click();
  await page.locator('div').filter({ hasText: /^🍪Graham Cracker\+\$0\.75$/ }).first().click();
  await page.getByRole('button', { name: '🛒 Add to Cart' }).click();
  await page.getByRole('link', { name: '🛒 Cart' }).click();
  await page.getByRole('button', { name: '💳 Proceed to Checkout' }).click();
  await page.getByRole('textbox', { name: 'Enter your first name' }).click();
  await page.getByRole('textbox', { name: 'Enter your first name' }).fill('Randy');
  await page.getByRole('textbox', { name: 'Enter your first name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter your last name' }).fill('Pagels');
  await page.getByRole('textbox', { name: 'Enter your last name' }).press('Tab');
  await page.getByRole('textbox', { name: 'your@email.com' }).fill('randy.pagels@xebia.com');
  await page.getByRole('textbox', { name: 'your@email.com' }).press('Tab');
  await page.getByRole('textbox', { name: '(555) 123-' }).fill('5551234567');
  await page.getByRole('textbox', { name: '(555) 123-' }).press('Tab');
  await page.getByRole('button', { name: 'Continue to Delivery →' }).click();
  await page.getByText('🏪Store PickupReady in 15').click();
  await page.getByRole('button', { name: 'Continue to Payment →' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).fill('Randy Pagels');
  await page.getByRole('textbox', { name: 'John Doe' }).press('Tab');
  await page.getByRole('textbox', { name: '5678 9012 3456' }).press('Tab');
  await page.getByRole('textbox', { name: '5678 9012 3456' }).click();
  await page.getByRole('textbox', { name: '5678 9012 3456' }).fill('1234 5678 9012 3456');
  await page.getByRole('textbox', { name: '5678 9012 3456' }).press('Tab');
  await page.getByRole('textbox', { name: 'MM/YY' }).fill('10/25');
  await page.getByRole('textbox', { name: 'MM/YY' }).press('Tab');
  await page.getByRole('textbox', { name: '123', exact: true }).fill('123');
  await page.getByRole('button', { name: '💳 Complete Order ($9.22)' }).click();
  await expect(page.locator('h2')).toContainText('Order Confirmed!');
  await page.getByRole('button', { name: '🏠 Back to Home' }).click();
});